# Generated by Django 6.0.6 on 2026-06-06 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('statut', models.CharField(choices=[('absent', 'Absent'), ('present', 'Présent'), ('justifie', 'Justifié'), ('retard', 'Retard')], default='absent', max_length=15)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='classes.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'absences',
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('url_document', models.FileField(blank=True, null=True, upload_to='justifications/')),
                ('commentaire_admin', models.TextField(blank=True, null=True)),
                ('absence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='absences.absence')),
                ('soumis_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications_soumises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'justifications',
            },
        ),
    ]
